import GreenPatch from "./GreenPatch";

export default function GreenPatchCollection() {
    return (
        <>
            {/* Background green patches - Mobile */}
            <div className="md:hidden">
                <GreenPatch
                    top="-10%"
                    left="-20%"
                    opacity="20"
                    width="200px"
                    height="200px"
                    animationType="float"
                    animationDuration={45}
                />
                <GreenPatch
                    top="40%"
                    right="-20%"
                    opacity="20"
                    width="200px"
                    height="200px"
                    animationType="float"
                    animationDuration={38}
                />
                <GreenPatch
                    top="80%"
                    left="-30%"
                    opacity="20"
                    width="200px"
                    height="200px"
                    animationType="float"
                    animationDuration={42}
                />
                <GreenPatch
                    top="-20%"
                    right="-20%"
                    opacity="20"
                    width="200px"
                    height="200px"
                    animationType="float"
                    animationDuration={50}
                />
                <GreenPatch
                    top="90%"
                    right="-40%"
                    opacity="20"
                    width="200px"
                    height="200px"
                    animationType="float"
                    animationDuration={46}
                />
            </div>

            {/* Background green patches - Tablet */}
            <div className="hidden md:block lg:hidden">
                <GreenPatch
                    top="-10%"
                    left="-20%"
                    opacity="20"
                    width="250px"
                    height="250px"
                    animationType="float"
                    animationDuration={45}
                />
                <GreenPatch
                    top="40%"
                    right="-20%"
                    opacity="20"
                    width="250px"
                    height="250px"
                    animationType="float"
                    animationDuration={38}
                />
                <GreenPatch
                    top="80%"
                    left="-30%"
                    opacity="20"
                    width="250px"
                    height="250px"
                    animationType="float"
                    animationDuration={42}
                />
                <GreenPatch
                    top="-20%"
                    right="-20%"
                    opacity="20"
                    width="250px"
                    height="250px"
                    animationType="float"
                    animationDuration={50}
                />
                <GreenPatch
                    top="90%"
                    right="-40%"
                    opacity="20"
                    width="250px"
                    height="250px"
                    animationType="float"
                    animationDuration={46}
                />
                <GreenPatch
                    top="25%"
                    left="40%"
                    opacity="8"
                    width="300px"
                    height="300px"
                    blur="2xl"
                    animationType="float"
                    animationDuration={52}
                />
                <GreenPatch
                    top="65%"
                    right="30%"
                    opacity="8"
                    width="300px"
                    height="300px"
                    blur="2xl"
                    animationType="float"
                    animationDuration={55}
                />
            </div>

            {/* Background green patches - Desktop */}
            <div className="hidden lg:block">
                <GreenPatch
                    top="-10%"
                    left="-20%"
                    opacity="20"
                    width="300px"
                    height="300px"
                    animationType="float"
                    animationDuration={45}
                />
                <GreenPatch
                    top="40%"
                    right="-20%"
                    opacity="20"
                    width="300px"
                    height="300px"
                    animationType="float"
                    animationDuration={38}
                />
                <GreenPatch
                    top="80%"
                    left="-30%"
                    opacity="20"
                    width="300px"
                    height="300px"
                    animationType="float"
                    animationDuration={42}
                />
                <GreenPatch
                    top="-20%"
                    right="-20%"
                    opacity="20"
                    width="300px"
                    height="300px"
                    animationType="float"
                    animationDuration={50}
                />
                <GreenPatch
                    top="90%"
                    right="-40%"
                    opacity="20"
                    width="300px"
                    height="300px"
                    animationType="float"
                    animationDuration={46}
                />
                <GreenPatch
                    top="25%"
                    left="40%"
                    opacity="8"
                    width="400px"
                    height="400px"
                    blur="2xl"
                    animationType="float"
                    animationDuration={52}
                />
                <GreenPatch
                    top="65%"
                    right="30%"
                    opacity="8"
                    width="400px"
                    height="400px"
                    blur="2xl"
                    animationType="float"
                    animationDuration={55}
                />
                <GreenPatch
                    top="10%"
                    right="20%"
                    opacity="5"
                    width="500px"
                    height="500px"
                    blur="3xl"
                    animationType="float"
                    animationDuration={60}
                />
                <GreenPatch
                    top="85%"
                    left="20%"
                    opacity="5"
                    width="500px"
                    height="500px"
                    blur="3xl"
                    animationType="float"
                    animationDuration={58}
                />
            </div>
        </>
    );
}
